spring:
  application:
    name: h2o
  liquibase:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
---
spring:
  config:
    activate:
      on-profile: LOCAL
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true

---
spring:
  config:
    activate:
      on-profile: DOCKER
  datasource:
    url: jdbc:postgresql://db:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true